feat: Central Agent Architecture - Micro Front Ends
newrelic/newrelic-browser-agent pull request #1266
Opened 2024-11-28 04:16 UTC by metal-messiah

Please add a one-paragraph summary here, suitable for a release notes description. This will help with documentation.
---

### Overview

### Related Issue(s)
https://new-relic.atlassian.net/browse/NR-380763
https://whimsical.com/data-flow-KeU9PdoS5Cfu55xVDhiYVD

### Context
#### Use register interface to capture data
https://github.com/user-attachments/assets/d516b6d4-fa9c-48e1-a38e-934764f4d618

#### Capture external data to both the target AND the container (config change on the container agent)

https://github.com/user-attachments/assets/60db4408-9a01-4173-bc48-0d5ebdf0c57b

#### NPM interface example

https://github.com/user-attachments/assets/80e4578a-71b1-45e4-846b-2de20d4c3156

### Testing

2025-03-14 15:31 UTC, cwli24 requested changes

2025-03-14 15:31 UTC, cwli24 commented on src/interfaces/registered-entity.js
the API methods here should be made into a new base similar to how main agent extends off microagent for it's API placeholder definition.

2025-03-14 15:31 UTC, cwli24 commented on src/loaders/api/api.js
> +      handle('err', [err, timestamp, false, customAttributes, !!replayRunning[agentRef.agentIdentifier], undefined, targetEntityGuid], undefined, FEATURE_NAMES.jserrors, agentRef.ee)
Nvm, I see that this is not exposed publicly. The `timestamp` should be local variables then rather than params in these functions.

2025-03-14 15:31 UTC, cwli24 commented on src/loaders/api/register-api.js
> +    }
I think you can just return undefined if the `target` is not valid. It's counterproductive to return a pseudo entity that just spams warning rather than user knowing right away something is wrong.

2025-03-14 15:31 UTC, cwli24 commented on src/interfaces/registered-entity.js
It's also not used aside from tests?

2025-03-14 15:31 UTC, cwli24 commented on src/loaders/api/register-api.js
> +    }
Maybe this should return a registeredEntity object? Some of these are getting defined multiple times, through placeholder and through actual implementation for both the main agent and MFE, and it's getting hard to keep track of which is which and from where.

2025-03-14 15:31 UTC, cwli24 commented on src/loaders/api/register-api.js
> +  })
It's very jarring mixing native Promise and the EE system and buried callback for this process. I roughly see what it's doing (only because I know the rest of the code well and how it plays out) but I still don't have a precise grasp on what's happening and when. Which is to say, this is overly complicated & convoluted. Let's talk about restructuring this.

2025-03-14 15:32 UTC, metal-messiah commented on package.json
> +      "interfaces/registered-entity": [
Platform team wants to dogfood with NPM

2025-03-14 15:33 UTC, metal-messiah commented on src/common/config/init.js
> +    external: { capture_registered_data: false },
This is a setting to be applied/controlled by the container agent, not the registered child.  It will affect the billing of the container agent and should not be controllable from external entities

2025-03-14 15:34 UTC, metal-messiah commented on src/common/harvest/__mocks__/harvest.js
probably a remnant from before the harvester change was merged.  Will remove

2025-03-14 15:34 UTC, metal-messiah commented on src/common/harvest/harvester.js
> +    if (cbFinished) cbFinished({ sent: false, targetApp, cbFinished: localOpts.cbFinished })
we can rename things.  Basically its the callback supplied originally from the register API

2025-03-14 15:35 UTC, metal-messiah commented on src/common/util/feature-flags.js
> +  const { app, ...flags } = rumResponse
easy way to exclude only the app property from the object

2025-03-14 15:38 UTC, metal-messiah commented on src/common/util/target.js
> +  if (target === undefined && allowUndefined) return true
unless you mean, anywhere that `isValidTarget` is called should have an extra check to see if target is `undefined` before calling?

2025-03-14 15:40 UTC, metal-messiah commented on src/common/util/target.js
> +  if (!target) return true
see https://github.com/newrelic/newrelic-browser-agent/pull/1266#discussion_r1995796498

lets discuss more

2025-03-14 15:42 UTC, metal-messiah commented on src/features/generic_events/aggregate/index.js
> +          if (!isValidTarget(this.agentRef.runtime.entityManager.get(targetEntityGuid))) return warn(47, targetEntityGuid)
I agree with the rest of what you said, but confused on this bit
`it ends up affecting the main entity which is a bad UX case`

If we cant find a bucket to put API data in, it should probably just get reported to the main agent (the behavior that exists today) or do you disagree? What do you have in mind there

2025-03-14 15:42 UTC, cwli24 commented on tests/dts/api.test-d.ts
> -expectError(() => expectType<any>(microAgent.wrapLogger))
The microagent type checks shouldn't be removed until microagent itself is actually removed

2025-03-14 15:44 UTC, metal-messiah commented on src/features/jserrors/aggregate/index.js
> +    const jsErrorEvent = [type, bucketHash, params, newMetrics, customAttributes, targetEntityGuid]
yeah i think this is a fair point.  I think we need to check if the error has a targetEntityGuid and if so, do not allow it to pass into the SPA chain (ie prevent it from ever getting a browser ixn ID.)

I just went through this same thing with AJAX detection, and handled it that way, so it would make sense to do the same for errors here.  I'll update that

2025-03-14 15:45 UTC, cwli24 commented on tests/components/generic_events/aggregate/index.test.js
> -    })
What caused this test change/deletion btw?

2025-03-14 15:46 UTC, metal-messiah commented on src/features/utils/entity-manager.js
> +    if (this.#defaultEntity.licenseKey === entity.licenseKey && this.#defaultEntity.applicationID === entity.applicationID && entity.entityGuid && !this.#defaultEntity.entityGuid) this.#defaultEntity
Ok, we can separate to another method i think that is the most straight forward

2025-03-14 15:47 UTC, metal-messiah commented on src/features/logging/aggregate/index.js
> +    if (target && !target.entityGuid) return warn(48)
Ok yeah, that description makes sense to me.  We can implement it that way

2025-03-14 15:50 UTC, metal-messiah commented on src/features/page_view_event/aggregate/index.js
> +    if (!this.agentRef.sharedAggregator) this.agentRef.sharedAggregator = new EventStoreManager(this.agentRef.runtime.entityManager, EventAggregator, respEntityGuid)
Agg-base initializes before the rum response is processed, so the ESM does not have access to the entity guid from the response.  That's the purpose of moving it here, to alleviate that into 1 step (constructor has access to entityGuid) -- otherwise you have this like, temporary state where data is getting added to a default store with no entity guid, and then an entity guid is added.  Felt more confusing to do it that way

2025-03-14 15:54 UTC, metal-messiah commented on src/loaders/api/api.js
> +      handle('err', [err, timestamp, false, customAttributes, !!replayRunning[agentRef.agentIdentifier], undefined, targetEntityGuid], undefined, FEATURE_NAMES.jserrors, agentRef.ee)
`The timestamp should be local variables then rather than params in these functions.`

This is done this way because the `log(` call in `register` is buffered before actually hitting the main agent's `log(`.  This method allows me to buffer the timestamp of the original call before forwarding it on to the main agent's API

2025-03-14 15:55 UTC, metal-messiah commented on src/loaders/api/api.js
> +    log: function log (message, { customAttributes = {}, level = LOG_LEVELS.INFO } = {}, targetEntityGuid, timestamp = now()) {
see https://github.com/newrelic/newrelic-browser-agent/pull/1266#discussion_r1995825852

2025-03-14 16:00 UTC, metal-messiah commented on src/features/page_view_event/aggregate/index.js
> +    registerHandler('api-pve', (cb, customAttibutes, target) => {
Would it make more sense to expose a promise that can be subscribed to in the register API?  The promise gets resolved when the main agent runs its rum call?

2025-03-14 16:03 UTC, metal-messiah commented on src/features/session_replay/shared/recorder.js
> +    this.#preloaded = [new RecorderEvents(this.shouldFix)]
ty

2025-03-14 16:07 UTC, metal-messiah commented on src/features/session_replay/shared/recorder.js
> +    const incompletes = this.parent.agentRef.init.session_replay.fix_stylesheets ? stylesheetEvaluator.evaluate() : 0
Allows it to bypass the expensive API checks, though this area could use some maintenance in a future work effort.  The shouldFix/init stuff is a bit confusing to traverse in here

2025-03-14 16:11 UTC, metal-messiah commented on src/features/utils/entity-manager.js
its a shared map with helpers built in to the get/set (and now a third method you suggested in a previous comment).  While we still have multiple agents on a page, this helps keep that from clashing from page level side-effecty object exports

2025-03-14 16:16 UTC, metal-messiah commented on src/features/soft_navigations/aggregate/index.js
> +    }, this.featureName, this.ee)
This allows us to wait for the `this.events` to be populated with the entityGuid by the rum call.  Everything should wait for drain in general, and before -- IPL event buffering was happening before the rum call.

2025-03-14 16:16 UTC, metal-messiah commented on src/features/soft_navigations/aggregate/index.js
> +    }, this.featureName, this.ee)
also why this was moved here, which allows this.events to have an entity guid https://github.com/newrelic/newrelic-browser-agent/pull/1266/files/6a1abe7a9057e4f82df68fff68ed0a02dcbebfd8#diff-8e79f8cdc78d2ee0a0abe1f0428fcf9cb1c0bcf92d5cb49485ea14c3ff31ad54R45

2025-03-14 16:19 UTC, metal-messiah commented on src/loaders/api/register-api.js
> +    }
I worry that risks potential to affect customer billing, since it will trigger JS errors to fire in the application if the APIs are undefined. This matches the behavior we use for setting the APIs in an empty state in the main agent interfaces as well

2025-03-14 16:19 UTC, metal-messiah commented on src/interfaces/registered-entity.js
not following what was meant here

2025-03-14 16:20 UTC, metal-messiah commented on src/interfaces/registered-entity.js
will be dogfooded by NR platform teams

2025-03-14 16:21 UTC, metal-messiah commented on src/loaders/api/register-api.js
> +  })
Yeah i mentioned in a previous comment that we could probably expose some promises in the PVE chain, maybe that would help this feel more simple (by way of everything is handling async the same way)

2025-03-14 16:24 UTC, metal-messiah commented on tests/components/generic_events/aggregate/index.test.js
> -    })
probably a merge remnant.  not sure here, will check

2025-03-14 18:07 UTC, metal-messiah commented on src/common/config/init.js
> +    external: { capture_registered_data: false },
could also extend this idea later to an `allow_registered_children` type of config to block register calls altogether or something too

2025-03-14 20:15 UTC, cwli24 commented on src/common/util/target.js
> +  if (target === undefined && allowUndefined) return true
to do: simplify this down by removing the 2nd parameter which is only used in `buildRegisterApi` so that `target === undefined` simply return true (with improved comment about "legacy" behavior)

2025-03-14 20:46 UTC, cwli24 commented on src/features/session_replay/shared/recorder.js
> +    const incompletes = this.parent.agentRef.init.session_replay.fix_stylesheets ? stylesheetEvaluator.evaluate() : 0
todo: this needs clean up? comment? logic check?

2025-03-14 20:53 UTC, cwli24 commented on src/features/soft_navigations/aggregate/index.js
> +    }, this.featureName, this.ee)
So yeah I think we can move this to be after this.drain

2025-03-18 03:07 UTC, metal-messiah commented on src/common/config/init.js
> +    external: { capture_registered_data: false },
https://github.com/newrelic/newrelic-browser-agent/pull/1266/commits/a65379249fbbc77117465041932d80b597f9a705

https://github.com/newrelic/newrelic-browser-agent/pull/1266/commits/9fe1fb60b9e8561fd9bc6e645f1b2373b6e4fcba

https://github.com/newrelic/newrelic-browser-agent/pull/1266/commits/6a75b22118eb3e0730eba189d52ec1aa07a1bbda

2025-03-18 03:08 UTC, metal-messiah commented on src/common/harvest/harvester.js
> +    if (cbFinished) cbFinished({ sent: false, targetApp, cbFinished: localOpts.cbFinished })
removed need for this with new pattern

2025-03-18 03:09 UTC, metal-messiah commented on src/common/harvest/harvester.js
> +    if (cbFinished) cbFinished({ sent: false, targetApp, cbFinished: localOpts.cbFinished })
4430c9f4d1eee04b59fffb5bdd5e9da822f828aa

2025-03-18 03:10 UTC, metal-messiah commented on src/common/harvest/__mocks__/harvest.js
d50c0d48

2025-03-18 03:19 UTC, metal-messiah commented on src/common/util/target.js
> +  if (target === undefined && allowUndefined) return true
b86c3b2f

2025-03-18 03:19 UTC, metal-messiah commented on src/features/generic_events/aggregate/index.js
> +          if (!isValidTarget(this.agentRef.runtime.entityManager.get(targetEntityGuid))) return warn(47, targetEntityGuid)
b86c3b2f

2025-03-18 03:30 UTC, metal-messiah commented on src/features/jserrors/aggregate/index.js
> +    const jsErrorEvent = [type, bucketHash, params, newMetrics, customAttributes, targetEntityGuid]
024cb352

2025-03-18 04:01 UTC, metal-messiah commented on src/features/soft_navigations/aggregate/index.js
> +    }, this.featureName, this.ee)
f27ee5b5

2025-03-18 04:03 UTC, metal-messiah commented on src/features/logging/aggregate/index.js
> +          'entity.guid': targetEntityGuid || this.agentRef.runtime.appMetadata?.agents?.[0]?.entityGuid, // browser entity guid as provided API target OR the default from RUM response if not supplied
971ed277

2025-03-18 04:05 UTC, metal-messiah commented on src/loaders/api/api.js
> +    addPageAction: function addPageAction (name, attributes, targetEntityGuid, timestamp = now()) {
980172a2

2025-03-18 04:06 UTC, metal-messiah commented on src/features/session_replay/aggregate/index.js
> +    if (!recorderEvents.events.length || (this.mode !== MODE.FULL) || this.blocked) return
76501fc5

2025-03-18 04:08 UTC, metal-messiah commented on src/features/session_replay/shared/recorder-events.js
> +    this.inlinedAllStylesheets = shouldInlineStylesheets
305fdf52

2025-03-18 04:08 UTC, metal-messiah commented on src/features/soft_navigations/aggregate/index.js
> +      this.interactionsToHarvest = this.events
https://github.com/newrelic/newrelic-browser-agent/commit/f27ee5b54b7e313d6be870bf50d7a01013086e0e

2025-03-18 04:09 UTC, metal-messiah commented on src/features/utils/aggregate-base.js
> +   * @param {Function} eventStore A method to create a new data store.
214289b1

2025-03-18 04:21 UTC, metal-messiah commented on src/loaders/api/register-api.js
> +    }
08b37627

2025-03-18 04:23 UTC, metal-messiah commented on tests/dts/api.test-d.ts
> -expectError(() => expectType<any>(microAgent.wrapLogger))
b98a47fe

2025-03-18 19:03 UTC, metal-messiah commented on src/features/utils/aggregate-base.js
> +      this.#setupEventStore(this.agentRef?.runtime?.appMetadata?.agents?.[0]?.entityGuid) // if there's no entity guid, wont dont anything, and will wait for rum flags
```suggestion
this.#setupEventStore(agentEntityGuid) // if there's no entity guid, wont dont anything, and will wait for rum flags
```

2025-03-28 17:32 UTC, metal-messiah commented on src/loaders/api/register-api.js
> +            clearTimeout(timeout)
add an ee unsubscribe from this cb at this stage

2025-04-03 14:23 UTC, cwli24 requested changes

2025-04-03 14:23 UTC, cwli24 commented on src/features/utils/aggregate-base.js
> +        this.events = this.agentRef.sharedAggregator ??= new EventStoreManager(this.agentRef, EventAggregator, entityGuid, 'shared_aggregator')
Needs to be moved back to `doOnceForAllAggregate`. The init cannot be moved here as other features like ajax may call on it alone. Don't create new dependency issues.

2025-04-03 14:23 UTC, cwli24 commented on src/interfaces/registered-entity.js
This doesn't increase CDN build size, right?

2025-04-03 14:23 UTC, cwli24 commented on src/loaders/api/register-api.js
This PR bumps the size of the lite loader by 3kB+. Then I thought why does lite loader even need all this register stuff; it doesn't have the features to make it meaningful, and the only real feature in it (PVT) is neither API-driven nor compatible with MFE context. So should all this be stripped from the lite build?

2025-04-04 18:12 UTC, metal-messiah commented on src/common/config/init.js
> +      duplicate_registered_data: false
I'll need to bring this up with the MFE group real quick, but this could work

2025-04-04 18:22 UTC, metal-messiah commented on src/features/jserrors/aggregate/index.js
> +    // Should only decorate "hasReplay" for the container agent, so check if the target matches the config
There is potential that they are not in the same account.  We could (and plan to) add entityGuids for the host and child data sets which could be used later to redirect, so that could be used here if we want to just keep the flag intact.  LMK

2025-04-04 18:29 UTC, metal-messiah commented on src/features/jserrors/aggregate/index.js
> +    if (targetEntityGuid) this.#storeJserrorForHarvest([...jsErrorEvent, targetEntityGuid], params.browserInteractionId !== undefined, params._softNavAttributes)
That's basically what is already happening here, just the steps are flipped.

It first checks if the main agent should capture the event (either because there is no target entity <or> its set up to duplicate) (`199-216`)
Then if there's a sub-entity guid, it saves it directly for that one.  (`220`)

They both do the same thing, just in opposite orders, so making this change wouldn't change the behavior at all, but if you feel like that is easier to understand we can change it.

2025-04-04 18:40 UTC, metal-messiah commented on src/features/page_view_event/aggregate/index.js
> +      this.processEntities(app.agents, targetApp)
It's actually not different than before, because the original behavior was that the IPL was added on `.done(` regardless of the rum flag state.  Both patterns rely on the `abort` logic to fire, and neither pattern would allow a harvest to leave since the agent would not have drained.

2025-04-04 18:41 UTC, metal-messiah commented on src/features/page_view_event/aggregate/index.js
> +      this.processEntities(app.agents, targetApp)
The goal here was to just ensure that the `this.events` exists before we try to buffer it, and the `this.events` has to wait for the entity to exist in the new system.

2025-04-04 18:42 UTC, metal-messiah commented on src/features/soft_navigations/aggregate/index.js
> +        setTimeout(() => agentRef.runtime.harvester.triggerHarvestFor(this), 0)
We can add the comment back, nbd

2025-04-04 18:46 UTC, metal-messiah commented on src/features/soft_navigations/aggregate/index.js
> +      if (this.interactionsToHarvest) this.interactionsToHarvest.add(ixn)
We've discussed this about 3 times now, but the event buffer enters a fragmented state if you set it up before knowing what it's entityGuid it (since all other event buffers rely on knowing what the entityGuid is).  You would have to have a "default" one (with no entity guid), and then later another with an entity guid (when you get the entity guid back from RUM call) -- It also creates two harvests for the same target while the buffer states are fragmented with mixed state between two. 

IMO those points were far more confusing while working through the issues of this PR, than it was to just wait for (all) event buffers to be backed up by a valid entity guid so that they can all be treated equally and the same throughout the agent

2025-04-04 18:49 UTC, metal-messiah commented on src/features/page_view_event/aggregate/index.js
> +    entities.forEach(agent => {
Yeah i think this just covers the basis that multiple entityguids are supported in the RUM response.  This allows that any of the 3 potentially returned in the RUM call could be used to report data to the target.  Its likely an edge case, but since thats the structure of the rum call i figured it would be better to not make assumptions that entity[0] is always the correct entityGuid a customer wants to use

2025-04-04 18:55 UTC, metal-messiah commented on src/features/utils/aggregate-base.js
> +        this.events = this.agentRef.sharedAggregator ??= new EventStoreManager(this.agentRef, EventAggregator, entityGuid, 'shared_aggregator')
This is another case where its easier to jsut treat event stores as needing the entityGuid from the start and makes more sense to treat as an equal here. (`doOnceForAllAggregate` occurs before we know what the entity guid is).  It makes more sense to just check if the sharedAggregator exists in AJAX before calling it than it does to preseve the fragmented state of the entity buffers / entity guids

2025-04-04 18:56 UTC, metal-messiah commented on src/loaders/api/register-api.js
This is the nature of the way the API is bundled, which is another thing weve discussed, but i wasnt going to mix that into this POC.

2025-04-04 19:03 UTC, metal-messiah commented on src/interfaces/registered-entity.js
this became outdated so not sure what this was pointing at

2025-04-04 19:04 UTC, metal-messiah commented on src/interfaces/registered-entity.js
in general, this file is not referenced by the CDN

2025-04-04 21:44 UTC, metal-messiah commented on src/common/config/init.js
> +      duplicate_registered_data: false
We should probably decorate these (and any other MFE specific configs) with `@experimental` JSDOC flags as well since they are subject to change

2025-04-06 00:20 UTC, cwli24 commented on src/common/config/init.js
> +      duplicate_registered_data: false
Well, as you know, these configs are a PITA to change & basically never go away. By nature, they're not experimental, so it's better to be sure you want them and that they're aptly named

2025-04-06 00:26 UTC, cwli24 commented on src/features/jserrors/aggregate/index.js
> +    // Should only decorate "hasReplay" for the container agent, so check if the target matches the config
I think parent-child relationship should be known by UI via query at that point, and it just being redundant billable data to add an extra information about parent entityguid. Anyways, no action needed here.

2025-04-06 00:35 UTC, cwli24 commented on src/features/jserrors/aggregate/index.js
> +    if (targetEntityGuid) this.#storeJserrorForHarvest([...jsErrorEvent, targetEntityGuid], params.browserInteractionId !== undefined, params._softNavAttributes)
Ok sorry for some reason, when I was writing this directly, it would because I _thought_ there's a case wherein this was doing more than it should.

So the ordering is fine; same end result. But you still need to change the subentity store to `this.#storeJserrorForHarvest([...jsErrorEvent, targetEntityGuid], false)` (fix the args passed in).

2025-04-06 00:40 UTC, cwli24 commented on src/features/soft_navigations/aggregate/index.js
> +      if (this.interactionsToHarvest) this.interactionsToHarvest.add(ixn)
I guess based off what you said what I mean is there maybe _should_ be a default buffer on init, which is that of the main entity, as the main entity is non negotiable. I was working under that assumption. You don't need to wait for the main entity guid to start its buffer instances, and when you do get it, you can just backfill it; I say this because you have the concept of a default app still in the system, so you're already implicitly treating the main entity as non-equal, if that makes sense. 

I don't anticipate this being a problem per se but I do anticipate problems deriving off this.

2025-04-06 00:42 UTC, cwli24 commented on src/features/utils/aggregate-base.js
> +        this.events = this.agentRef.sharedAggregator ??= new EventStoreManager(this.agentRef, EventAggregator, entityGuid, 'shared_aggregator')
See response to the other thread about having a default entity & corresponding data stores like before; This will ride on the same outcome.

2025-04-06 00:43 UTC, cwli24 approved these changes
Some threads left to address but not big issues. I'll unblock my request change for this PR since I'll be OoO.

2025-04-08 16:44 UTC, metal-messiah commented on src/features/soft_navigations/aggregate/index.js
> +      if (this.interactionsToHarvest) this.interactionsToHarvest.add(ixn)
Yeah lets revisit this at some point because you could be right, but for now I dont think this will have a tangible outcome other than code mgmt

2025-04-08 17:39 UTC, ptang-nr approved these changes
🚢

2025-04-08 18:25 UTC, merged