feat: Add auto-logging feature
newrelic/newrelic-browser-agent pull request #1274
Opened 2024-12-11 17:34 UTC by ptang-nr

The auto-logging feature builds on top of the current API calls `log` and `wrapLogger`.  The api calls continue to provide a way to add custom attributes as needed.  Otherwise, customers may simply configure browser logs (on/off, logging level, and sampling rates), which will capture logging statements from the browser `console` across a given session automatically.
---

### Overview

This PR includes work that:
- wraps the various logging methods of the console
- aggregates logging events according to the `log` flag received from rum call to BCS
- persists logging mode across active [session](https://docs.newrelic.com/docs/browser/browser-monitoring/page-load-timing-resources/cookie-collection-session-tracking/) and will auto-disable upon session expiration after 4 hours or session inactivity after 30 minutes.

### Related Issue(s)

https://new-relic.atlassian.net/browse/NR-323591
https://new-relic.atlassian.net/browse/NR-323597
https://new-relic.atlassian.net/browse/NR-341932

### Testing

- Extended the existing e2e tests for logging harvests:
  - pre-load
  - post-load
  - harvests that are too large
  - harvest early

- Extended existing logging aggregate unit and e2e tests around handling the flag. Includes tests for each logging mode to ensure log messages of equal or higher levels are collected. For example, if the log flag = 3 (INFO), then collect console.error, console.warn, console.info, and console.log events.

- Extended existing tests to ensure no harvests when rum flag = 0 and events are drained.

2024-12-11 17:36 UTC, ptang-nr commented on .github/actions/build-ab/templates/postamble.js
> +
This was removed for the experimental publish to staging

2025-01-02 17:27 UTC, cwli24 commented on src/features/utils/aggregate-base.js
Since session isn't applicable to all (or even a majority) of the features, I think you should leave it out of the base class

2025-01-08 18:17 UTC, ptang-nr commented on src/features/utils/aggregate-base.js
(ah, just saw this EOD yesterday) - when i introduced it at the time, I hadn't the association that aggregate-base should only contain code relevant to all/majority of features, just methods/attrs that could be common and it's up to specific features whether they use 'em 🤔 

I can move the logic back into the feat agg constructors.  Can't really think of anywhere else or anything i want to introduce yet. Lmk if you have other thoughts!

2025-01-28 17:55 UTC, metal-messiah requested changes
This is my approval, but this needs to wait until tentative GA date as discussed internally.  Adjacent teams doing final checks.  Blocking until that is reached

2025-02-18 15:37 UTC, metal-messiah approved these changes

2025-02-18 15:49 UTC, merged