Prevent webpack mangling nrWrapper method
newrelic/newrelic-browser-agent pull request #352
Opened 2022-12-16 18:40 UTC by patrickhousley

### Overview

Updating the webpack config so the `nrWrapper` method is not mangled. This was preventing the `jserrors` feature from properly excluding the `nrWrapper` and subsequent agent code from error stack traces.

Also including an update to the debug script the asset test server injects that was causing errors in IE11. IE does not support template strings.

### Related Issue(s)

https://issues.newrelic.com/browse/NEWRELIC-5929

### Testing

Run the JIL test suite in GH. Optionally, should probably also run the polyfills tests.

2022-12-19 17:43 UTC, metal-messiah approved these changes
Glad we caught this.  Nice work, looks good.

2022-12-20 19:04 UTC, cwli24 approved these changes
Added more info to JIRA ticket, also big thumbs up

2022-12-20 19:43 UTC, cwli24 approved these changes

2022-12-21 13:34 UTC, cwli24 approved these changes
Really need to have a changelog checklist somewhere lol, I keep forgetting to check for it.

2022-12-21 16:51 UTC, metal-messiah commented
> Really need to have a changelog checklist somewhere lol, I keep forgetting to check for it.

Same

2022-12-21 16:55 UTC, metal-messiah submitted a review, later dismissed

2022-12-21 19:01 UTC, metal-messiah submitted a review, later dismissed

2022-12-21 20:25 UTC, cwli24 requested changes

2022-12-22 15:54 UTC, cwli24 approved these changes

2023-01-03 18:24 UTC, metal-messiah approved these changes

2023-01-03 18:25 UTC, merged