NR-78867: Safe sessionStorage writes
newrelic/newrelic-browser-agent pull request #367
Opened 2023-01-13 01:10 UTC by patrickhousley

### Overview

Wrapping our access of and write to sessionStorage in a `try..catch` to ensure it does not cause the agent to crash when sessionStorage is not available or when the quota has been exceeded or set to 0. Safari has been know to set the sessionStorage quota to 0 in private browsing windows. This was causing the agent to crash and the API to not be attached to the window.newrelic object.

### Related Issue(s)

https://issues.newrelic.com/browse/NR-78867

### Testing

A functional test has been added to ensure we no longer have this issue. To reproduce the error, comment out the `try..catch` wrapper added in this PR, rebuild, and load the new test page. After loading, check the window.newrelic object to see if the API methods were added.

2023-01-17 19:50 UTC, metal-messiah approved these changes

2023-01-18 16:29 UTC, cwli24 requested changes

2023-01-18 16:29 UTC, cwli24 commented on packages/browser-agent-core/src/common/window/session-storage.js
> +  try {
Per huddle, the problematic line that triggers the DOM exception is actually above where ss is being defined as a side effect:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/28714891/213235282-055ccdb3-edaf-4239-8cbd-98f4f2ee4733.png">

My suggestion is to wrap that instead and leave it as undefined if error thrown (as the getCurrent... function is already setup to handle a null `ss`) like:
```javascript
let ss;
try {
  if (isBrowserScope) ss = window.sessionStorage;
  // else, leave it undefined
} catch (err) {
  // exception thrown, then also leave it undefined
}
```

2023-01-18 19:29 UTC, metal-messiah commented
I used this verbiage in the release-notes:
```
### Fix check for sessionStorage object
Ensure the agent does not crash when sessionStorage is not available or when the quota has been exceeded or set to 0. Safari has been known to set the sessionStorage quota to 0 in private browsing windows.
```

Do you want to add that to the CHANGELOG.md file as well?

2023-01-18 19:56 UTC, cwli24 approved these changes

2023-01-18 19:57 UTC, merged