Bind navigator to sendBeacon to prevent illegal invocation errors on …
newrelic/newrelic-browser-agent pull request #374
Opened 2023-01-19 17:10 UTC by metal-messiah

### Overview

Some browser versions will throw errors if sendBeacon does not have the navigator scope bound to it.  This is just a fail-safe action to try to support those browsers. See `Links` for more context 

### Related Issue(s)

https://issues.newrelic.com/browse/NEWRELIC-4686

### Links 
[Issues with Navigator Context](https://xgwang.me/posts/you-may-not-know-beacon/#it-may-throw-error%2C-be-sure-to-catch)
[How next.js handled this](https://github.com/vercel/next.js/pull/26601/files)

### Testing

final-harvest.test.js tests the calling of sendBeacon on unload.  The behavior should be unchanged in our testing suite, and this ticket should just be treated as a "try our best to do-no-harm" effort and nothing more.

2023-01-19 22:57 UTC, cwli24 commented on packages/browser-agent-core/src/common/util/submit-data.js
> +  const send = globalScope.navigator.sendBeacon.bind(navigator)
(minor note: `navigator` cannot be reassigned & ought to be safe as is)
<img width="832" alt="image" src="https://user-images.githubusercontent.com/28714891/213580724-fd0164c9-f15f-4582-9a6a-f6efb6bcf706.png">

2023-01-20 13:36 UTC, patrickhousley approved these changes

2023-01-23 16:59 UTC, cwli24 requested changes

2023-01-23 16:59 UTC, cwli24 commented on packages/browser-agent-core/src/common/util/submit-data.js
> +  const send = globalScope.navigator.sendBeacon.bind(navigator)
Update: actually can you just remove import/use of `globalScope`? That module is meant for APIs interchangeable between window and workers. In this case, the `navigator.sendBeacon` is only relevant to the window, so it should just be `window.navigator.sendBeacon.bind(navigator)`.

2023-01-30 19:35 UTC, cwli24 approved these changes

2023-02-01 18:33 UTC, metal-messiah commented
Changelog needed

2023-02-01 20:09 UTC, merged