NEWRELIC-6934: Fix wrapped promise instanceof for async functions
newrelic/newrelic-browser-agent pull request #410
Opened 2023-02-17 21:25 UTC by patrickhousley

### Overview

Adding support for `instanceof` comparison of wrapped promises created from native `async/await` functionality.

### Related Issue(s)

https://issues.newrelic.com/browse/NEWRELIC-6934
#409

### Testing

Added an integration test to check the `instanceof` comparison.

2023-03-01 22:14 UTC, bjfield requested changes
Other than a comment that could be clarified in wrap-promise.js, looks great.

2023-03-01 22:25 UTC, metal-messiah approved these changes

2023-03-01 22:29 UTC, bjfield commented on src/common/wrap/wrap-promise.js
> +     *  In addition, this affects the fetch() promise too.
```suggestion
     * so we have to modify the original prototype. This ensures that promises returned from async functions execute
     * the same instance methods as promises created with "new Promise()", and also that instanceof async() is
     * the global Promise (see GH issue #409). This also affects the promise returned from fetch().
```

2023-03-01 22:32 UTC, bjfield approved these changes

2023-03-01 22:37 UTC, cwli24 approved these changes

2023-03-01 22:42 UTC, merged

2023-03-02 17:33 UTC, samdenty commented
is this released yet?

2023-03-02 17:34 UTC, patrickhousley commented
Hey @samdenty not yet. We just merged the fix and are getting ready for the release of version 1227. We don't have an ETA just yet as we are also working on testing out release 1226 right now.