Js 7724/jil cleanup
newrelic/newrelic-browser-agent pull request #43
Opened 2021-05-10 22:42 UTC by metal-messiah

### Overview
This PR does a clean up of some basic functionality for JIL.  Its adds:
- Simplified interface commands for running tests
    - All tests can be ran using `npm run test`
    - `npm run test` can accept the same params as the cli script
        - NOTE: you must separate the cli params from the npm script params using empty double dashes (`--`)
    - A script command for spinning up the JIL-Server `npm run test-server`
- Updates the documentation
    - To match the changes
    - Clear up formatting
- Fortifies the NPM Install command, which now first installs the root package dependencies, and then runs a postscript which recursively traverses the children directories looking for package.json files, and subsequently installing them.

### Related Issue
[JIRA](https://newrelic.atlassian.net/browse/JS-7724)

### Testing
- Please clear your node_modules and try a `npm install`
    - Please check that node_modules exist in root and in `tools/jil`
- Please read the updated `README.md` and try some of the test commands using `npm run test` as the base command.
    - Make sure the readme makes sense, and that the tests execute as expected.
    - Please try the test server command
    - Please try running the tests directly from the cli file as before and ensure that still works as well.

2021-05-10 23:16 UTC, metal-messiah commented
It would be helpful if you review the recursive NPM install and ensure this is a better solution.  I was told the problem is that pre-post NPM installs were only sporadically successful with JIL.  This may help eliminate that problem.

2021-05-11 21:12 UTC, martinkuba commented
This all looks good to me. The post-install script being recursive is a little unnecessary, but I am not opposed to it.

2021-05-11 21:13 UTC, martinkuba requested changes

2021-05-11 21:13 UTC, martinkuba commented on post-installer.js
> +    console.log(`\n================================\n${msg}\n================================\n`)
We use 2 spaces for indents, I would recommend changing to be consistent.

2021-05-11 23:28 UTC, merged