chore: jests tests for id generators
newrelic/newrelic-browser-agent pull request #466
Opened 2023-04-14 02:10 UTC by patrickhousley

### Overview

Wrote jest unit tests for the id generators.

### Related Issue(s)

https://issues.newrelic.com/browse/NEWRELIC-8093

### Testing

2023-04-14 20:50 UTC, bjfield requested changes

2023-04-14 20:50 UTC, bjfield commented on src/common/ids/id.test.js
> +
```suggestion

test('id values increment sequentially', () => {
  const inputA = {}
  const inputB = {}

  const resultA = idFn(inputA)
  const resultB = idFn(inputB)

  expect(resultA - resultB).toEqual(-1)
})

```

2023-04-18 13:00 UTC, metal-messiah approved these changes

2023-04-19 16:32 UTC, bjfield approved these changes

2023-04-20 16:09 UTC, merged