feat: Add API: setApplicationVersion
newrelic/newrelic-browser-agent pull request #639
Opened 2023-08-14 22:16 UTC by metal-messiah

Add api method to top-level interface to allow the setting of application version across all outgoing payloads
---

### Overview
This PR adds a method to add a standardized application version property to all outgoing payloads.

### Related Issue(s)
https://issues.newrelic.com/browse/NR-150937

### Testing
A new jest test has been added to validate this behavior.  Other browser tests checking existing API method behaviors should continue passing.

2023-08-14 22:17 UTC, patrickhousley requested changes
Missing types updates.

2023-08-15 04:50 UTC, metal-messiah commented
> Missing types updates.

Type defs have been updated

2023-08-15 13:57 UTC, patrickhousley commented on src/loaders/agent-base.js
> +   */
```suggestion
  /**
   * Adds a user-defined application version string to subsequent events on the page.
   * This decorates all payloads with an attribute of `application.version` which is queryable in NR1.
   * {@link https://docs.newrelic.com/docs/browser/new-relic-browser/browser-apis/setapplicationversion/}
   * @param {string|null} value A string identifier for the application version, useful for
   * tying all browser events to a specific release tag. The value parameter does not
   * have to be unique. Passing a null value unsets any existing value.
   */
```

2023-08-15 13:58 UTC, patrickhousley approved these changes
Just one recommended change to make the comment block shorter.

2023-08-15 17:04 UTC, merged